//! GB2312 CJK bitmap fonts, generated by `tools/generate_cjk_font.py` from
//! Noto Sans SC (SIL OFL 1.1 - see `assets/FONT_LICENSE.txt`).
//!
//! Two sizes share one 94x94 GB2312 cell grid:
//!   - 16x16 (32 bytes/cell, HZK16 layout: 16 rows x 2 bytes, MSB first,
//!     bit 1 = ink) - rendered by `Canvas::draw_text_prop` for CJK chars.
//!   - 12x12 (24 bytes/cell: 12 rows x 2 bytes, same bit order) - rendered
//!     by `Canvas::draw_text_small`.
//!
//! The ASCII range keeps the existing proportional 8x16 / 5x7 fonts; this
//! module only covers GB2312-encodable CJK + punctuation. A char with no
//! glyph in either font falls back to blank (the ASCII fonts' behavior).

/// 16x16 glyph bytes per cell (16 rows x 2 bytes).
pub const CELL_BYTES_16: usize = 32;
/// 12x12 glyph bytes per cell (12 rows x 2 bytes).
pub const CELL_BYTES_12: usize = 24;
/// Advance width of a 16x16 CJK glyph at scale 1 (16px cell + 1px gutter).
pub const WIDTH_16: usize = 17;
/// Advance width of a 12x12 CJK glyph (12px cell + 1px gutter).
pub const WIDTH_12: usize = 13;

static FONT_16: &[u8] = include_bytes!("../assets/hzk16.bin");
static FONT_12: &[u8] = include_bytes!("../assets/hzk12.bin");
/// Sorted (u16 codepoint, u16 cell_index) little-endian pairs.
static INDEX: &[u8] = include_bytes!("../assets/cjk_index.bin");

fn cell_index(character: char) -> Option<u16> {
    let code = character as u32;
    if code > u32::from(u16::MAX) {
        return None;
    }
    let target = code as u16;
    let entries = INDEX.len() / 4;
    let mut lo = 0usize;
    let mut hi = entries;
    while lo < hi {
        let mid = (lo + hi) / 2;
        let (cp, _) = entry(mid);
        if cp < target {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    if lo < entries {
        let (cp, cell) = entry(lo);
        if cp == target {
            return Some(cell);
        }
    }
    None
}

fn entry(i: usize) -> (u16, u16) {
    let off = i * 4;
    (
        u16::from_le_bytes([INDEX[off], INDEX[off + 1]]),
        u16::from_le_bytes([INDEX[off + 2], INDEX[off + 3]]),
    )
}

/// 16x16 glyph rows for `character`, or `None` when it has no CJK glyph.
pub fn glyph16(character: char) -> Option<&'static [u8]> {
    let cell = cell_index(character)? as usize;
    let start = cell * CELL_BYTES_16;
    Some(&FONT_16[start..start + CELL_BYTES_16])
}

/// 12x12 glyph rows for `character`, or `None` when it has no CJK glyph.
pub fn glyph12(character: char) -> Option<&'static [u8]> {
    let cell = cell_index(character)? as usize;
    let start = cell * CELL_BYTES_12;
    Some(&FONT_12[start..start + CELL_BYTES_12])
}

/// Whether `character` has a CJK glyph (and thus a fixed-width advance
/// instead of the ASCII fonts' proportional one).
pub fn is_cjk(character: char) -> bool {
    cell_index(character).is_some()
}
